In [1]:
from core.narx import NARX
from core.simulator import Simulator
import tensorflow as tf
import numpy as np

In [2]:
from collections import deque

In [3]:
import gym

In [4]:
replay_buffer = deque()

In [5]:
episodes = 10
env = gym.make('Pendulum-v0')

[2018-04-19 01:04:10,415] Making new env: Pendulum-v0


In [6]:
for i_episode in range(episodes):
    prev_observation = env.reset()
    
    for t in range(200):
#         env.render()
#         print(prev_observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        replay_buffer.append((prev_observation, action, observation, reward, done))
        prev_observation = observation
        if done:
            break

In [7]:
len(replay_buffer)

2000

In [8]:
sim = Simulator(5, env)

sim.train(replay_buffer, verbose=1)

sim.reset()

sim.step(np.random.rand(1,1)*4-2)

Done finished sleep cycle
0.9980130950653158
-0.06300684151859229
0.4970829816417306


(array([[0.10173653, 0.06729969, 0.19218041]], dtype=float32),
 array([[-0.02479502]]),
 True)

In [9]:


observation = env.reset() 
prev_actions = []
prev_observations = []
for t in range(5):
    action = env.action_space.sample()
    prev_actions.append(action)
    prev_observations.append(observation)
    
    observation, reward, done, info = env.step(action)

In [10]:
prev_actions = np.concatenate(prev_actions)

In [11]:
prev_observations = np.concatenate(prev_observations)

In [12]:
load_queue = np.concatenate([prev_actions,prev_observations])[None]

In [13]:
load_queue

array([[-1.12892055,  0.3489989 ,  1.9504532 ,  1.80346818, -0.62811406,
         0.07462726,  0.9972115 , -0.49616925,  0.07051806,  0.9975105 ,
         0.08240129,  0.02642936,  0.99965068,  0.88288401, -0.06977033,
         0.99756308,  1.92519   , -0.21532164,  0.97654318,  2.94388254]])

In [28]:
np.array([1,1,8]*5)

array([1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8, 1, 1, 8])

In [20]:
real_response = []
sim_response = []
sim.load_starting_queue(load_queue)


(1, 20)


In [22]:
s_observation, s_reward, s_done = sim.step(action[None])

0.8429627
-0.87742454
-0.73056203


In [23]:
observation

array([-0.38584616,  0.92256314,  3.58207282])

In [24]:
s_observation

array([[ 0.830807  , -0.74814457, -0.8343003 ]], dtype=float32)

In [21]:
sim.narx.queue.eval()

array([[-1.1289206 ,  0.3489989 ,  1.9504532 ,  1.8034682 , -0.62811404,
         0.07462726,  0.9972115 , -0.49616924,  0.07051806,  0.9975105 ,
         0.08240129,  0.02642936,  0.99965066,  0.882884  , -0.06977033,
         0.99756306,  1.92519   , -0.21532165,  0.9765432 ,  2.9438825 ]],
      dtype=float32)

In [ ]:
for t in range(195):
    action = env.action_space.sample()
    prev_observation = observation
    if done:
        break

In [15]:
sim.reset()

array([[-0.29402205,  0.95579864,  0.59807615]])

In [18]:
sim.narx.queue.eval()

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.98705155,  0.16040353, -0.2715446 ]],
      dtype=float32)

In [26]:
a = np.array([1,2,3])[None]
replay_buffer[0][2]

array([ 0.70406087, -0.71013962, -0.02831643])

In [ ]:
sim.reset()

In [33]:
a = np.random.rand(3,1)

In [42]:
_in = np.array([1,2,3])
_out = np.array([1])[None]

In [35]:
a.shape
_in.shape

(2, 3)

In [36]:
np.matmul(_in, a)

array([[1.9419268 ],
       [5.21315199]])

In [38]:
env.reset()[None]

array([[ 0.58793645, -0.80890712, -0.50442568]])

In [44]:
_in[None].shape

(1, 3)

In [51]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [55]:
a.reshape(3,-1).reshape([-1,3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [56]:
b = a.reshape(-1)

In [57]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [69]:
a.reshape(b.shape)[0:12]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
[replay_buffer[0 + m][0] for m in range( 5-1,-1,-1)]

[array([ 0.73166181, -0.6816678 , -0.82969376]),
 array([ 0.75930298, -0.65073726, -0.36857072]),
 array([ 0.77116551, -0.63663471,  0.04724729]),
 array([ 0.76965939, -0.63845471,  0.3969747 ]),
 array([ 0.7568361 , -0.65360471,  0.85789013])]

In [20]:
replay_buffer[0][0]

array([ 0.7568361 , -0.65360471,  0.85789013])

In [21]:
[replay_buffer[0 + m][0] for m in range(5)]

[array([ 0.7568361 , -0.65360471,  0.85789013]),
 array([ 0.76965939, -0.63845471,  0.3969747 ]),
 array([ 0.77116551, -0.63663471,  0.04724729]),
 array([ 0.75930298, -0.65073726, -0.36857072]),
 array([ 0.73166181, -0.6816678 , -0.82969376])]